#!/usr/bin/env node
const fs = require("fs/promises")
const globby = require("globby")
const makeDir = require("make-dir")
const path = require("path")
const svgo = require("svgo")

const REPO_ROOT = path.join(__dirname, ".")

async function main() {
    let icons = await globby("./src/**/*.svg", {
        cwd: REPO_ROOT,
        absolute: true,
        onlyFiles: true,
        unique: true,
    })

    for (let icon of icons) {
        let relative = path.relative(path.join(REPO_ROOT, "src"), icon)
        let contents = await fs.readFile(icon, "utf-8")

        let output = svgo.optimize(contents, {
            full: false,
            multipass: false,
            js2svg: { pretty: true, indent: 2 },
            plugins: [
                {
                    name: "symbolize",
                    type: "full",
                    fn: (ast) => {
                        return {
                            ...ast,
                            children: [
                                {
                                    type: "comment",
                                    value: " Generated by `npm run gen:icons`, do not modify. ",
                                },
                                ...ast.children.map((child) => {
                                    if (child.type === "element" && child.name === "svg") {
                                        let { xmlns, ...attributes } = child.attributes
                                        return {
                                            ...child,
                                            attributes: { xmlns },
                                            children: [
                                                {
                                                    type: "element",
                                                    name: "symbol",
                                                    attributes: {
                                                        ...attributes,
                                                        id: "wpds-asset-id",
                                                        fill: "currentColor"
                                                    },
                                                    children: child.children,
                                                },
                                            ],
                                        }
                                    } else {
                                        return child
                                    }
                                }),
                            ],
                        }
                    },
                },
            ],
        }).data


        let newPath = path.join(REPO_ROOT, "public/icons-embed", relative)

        await makeDir(path.dirname(newPath))
        await fs.writeFile(newPath, output)
    }
}

main().catch((err) => {
    console.error(err)
    process.exit(1)
})